---
- name: Converge
  hosts: all
  tasks:
    - name: "Include palekiwi.dotfiles"
      ansible.builtin.include_role:
        name: "palekiwi.dotfiles"
      vars:
        dotfiles_repo: https://github.com/palekiwi/dotfiles
