---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.fedoraproject.org/fedora-toolbox:37
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
